apiVersion: v1
kind: Secret
metadata:
  name: aap-node-management-token
  namespace: autoscale-node-automation
  annotations:
    kubernetes.io/service-account.name: aap-node-management-sa
type: kubernetes.io/service-account-token
